=== SP7-Ritmare/EDI-NG_client/templates/edi_template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified"
           vc:minVersion="1.1" attributeFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:element name="template">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="settings"/>
        <xs:element ref="endpointTypes"/>
        <xs:element ref="datasources"/>
        <xs:element maxOccurs="unbounded" ref="group"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="userInterfaceLanguage"/>
        <xs:element ref="metadataLanguage"/>
        <xs:element ref="metadataEndpoint"/>
        <xs:element ref="sparqlEndpoint"/>
        <xs:element ref="requiresValidation"/>
        <xs:element ref="baseDocument"/>
        <xs:element ref="xsltChain"/>
        <xs:element ref="codelistQuery"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="userInterfaceLanguage">
    <xs:complexType>
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadataLanguage">
    <xs:complexType>
      <xs:attribute name="selectionItem" use="required" type="xs:IDREF"/>
      <!-- <xs:attribute ref="xml:lang" use="required"/> -->
    </xs:complexType>
  </xs:element>
  <xs:element name="metadataEndpoint" type="xs:anyURI"/>
  <xs:element name="sparqlEndpoint" type="xs:anyURI"/>
  <xs:element name="requiresValidation" type="xs:boolean"/>
  <xs:element name="baseDocument" type="xs:string"/>
  <xs:element name="xsltChain">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="xslt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="xslt" type="xs:anyURI"/>
  <xs:element name="codelistQuery" type="xs:string"/>
  <xs:element name="endpointTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="endpointType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="endpointType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameters"/>
      </xs:sequence>
      <xs:attribute ref="xml:id" use="required"/>
      <xs:attribute name="method" use="required" type="xs:NCName"/>
      <xs:attribute name="queryParameter" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datasources">
    <xs:complexType>
      <xs:all>
        <xs:element maxOccurs="unbounded" ref="codelist"/>
        <xs:element maxOccurs="unbounded" ref="sparql"/>
        <xs:element maxOccurs="unbounded" ref="singleton"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="codelist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="uri"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:IDREF"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="uri" type="xs:anyURI"/>
  <xs:element name="sparql">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="query"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:IDREF"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="singleton">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="query"/>
        <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="endpointType" use="required" type="xs:IDREF"/>
      <xs:attribute name="triggerItem" use="required" type="xs:NCName"/>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="help"/>
          <xs:element ref="label"/>
          <xs:element maxOccurs="unbounded" ref="element"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute ref="xml:id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="element">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="help"/>
          <xs:element ref="label"/>
        </xs:choice>
        <xs:element ref="hasRoot"/>
        <xs:element ref="produces"/>
      </xs:sequence>
      <xs:attribute name="isMandatory" use="required" type="xs:boolean"/>
      <xs:attribute name="isMultiple" use="required" type="xs:boolean"/>
      <xs:attribute ref="xml:id" use="required"/>
      <xs:attribute name="alternativeTo" use="optional" type="xs:IDREF"/>
    </xs:complexType>
    <xs:key name="ID">
      <xs:selector xpath="element"/>
      <xs:field xpath="@xml:id"/>
    </xs:key>
    <xs:keyref name="IDREF" refer="ID">
      <xs:selector xpath="element"/>
      <xs:field xpath="@alternativeTo"/>
    </xs:keyref>
  </xs:element>
  <xs:element name="hasRoot" type="xs:string"/>
  <xs:element name="produces">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="help"/>
          <xs:element ref="label"/>
        </xs:choice>
        <xs:element ref="hasPath"/>
        <xs:choice minOccurs="0">
          <xs:element ref="defaultValue"/>
          <xs:element ref="field"/>
          <xs:element ref="hasValue"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="datasource" type="xs:IDREF"/>
      <xs:attribute name="hasDatatype" use="required" type="xs:NCName"/>
      <xs:attribute name="hasIndex" use="required" type="xs:integer"/>
      <xs:attribute name="isFixed" use="required" type="xs:boolean"/>
      <xs:attribute name="outIndex" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="hasPath" type="xs:anyURI"/>
  <xs:element name="defaultValue" type="xs:anyType"/>
  <xs:element name="field" type="xs:NCName"/>
  <xs:element name="hasValue" type="xs:string"/>
  <xs:element name="url" type="xs:anyURI"/>
  <xs:element name="query" type="xs:string"/>
  <xs:element name="label">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="help">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SP7-Ritmare/EDI-NG_client/src/assets/templates/SensorML101_vTEST-phyto_newSchema.xml
<?xml version="1.0" encoding="UTF-8"?><template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="edi_template.xsd">
<settings>
<userInterfaceLanguage xml:lang="it"/>
<metadataLanguage selectionItem="ling_md_1"/>
<metadataEndpoint>https://enygma.it/edi/</metadataEndpoint>
<sparqlEndpoint>http://sparql/sparql.get-it.it/sparql</sparqlEndpoint>
<requiresValidation>false</requiresValidation>
<baseDocument><![CDATA[
            
            
            <swes:InsertSensor xmlns:sos="http://www.opengis.net/sos/2.0"
    xmlns:sml="http://www.opengis.net/sensorML/1.0.1"
    xmlns:swe="http://www.opengis.net/swe/1.0.1"
    xmlns:tns="http://www.w3.org/2005/08/addressing"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:gco="http://www.isotc211.org/2005/gco"
    xmlns:gss="http://www.isotc211.org/2005/gss"
    xmlns:gmd="http://www.isotc211.org/2005/gmd"
    xmlns:gml="http://www.opengis.net/gml"
    xmlns:swes="http://www.opengis.net/swes/2.0"
    xmlns:om="http://www.opengis.net/om/2.0"
    xmlns:ows="http://www.opengis.net/ows/1.1"
    xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"
    xmlns:gsr="http://www.isotc211.org/2005/gsr"
    xmlns:gts="http://www.isotc211.org/2005/gts"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opengis.net/sos/2.0/ http://schemas.opengis.net/sos/2.0/sosInsertSensor.xsd http://www.opengis.net/swes/2.0 http://schemas.opengis.net/swes/2.0/swes.xsd" version="2.0.0" service="SOS">
    <swes:procedureDescriptionFormat>http://www.opengis.net/sensorML/1.0.1</swes:procedureDescriptionFormat>
    <swes:procedureDescription>
        <!-- Licence CC By SA 3.0  http://creativecommon.org/licences/by-SA/3.0 -->
        <sml:SensorML version="1.0.1">
        
        </sml:SensorML>
    </swes:procedureDescription>
<swes:observableProperty></swes:observableProperty>
<swes:metadata>
<sos:SosInsertionMetadata>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_CategoryObservation</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_CountObservation</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_TextObservation</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_TruthObservation</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_GeometryObservation</sos:observationType>
<sos:observationType>http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_SWEArrayObservation</sos:observationType>
<sos:featureOfInterestType>http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingPoint</sos:featureOfInterestType>
</sos:SosInsertionMetadata>
</swes:metadata>
</swes:InsertSensor>
        
        ]]></baseDocument>
<xsltChain>
            <xslt>http://sp7.irea.cnr.it/jboss/MDService/rest/SensorML101.xsl?version=2.00</xslt>
        </xsltChain>
</settings>
<endpointTypes>
<endpointType xml:id="virtuoso" method="GET" queryParameter="query">
<parameters>
<parameter name="format" value="application/sparql-results+json"/>
<parameter name="save" value="display"/>
<parameter name="fname" value="undefined"/>
</parameters>
</endpointType>
<endpointType xml:id="sparqlTemaTres" method="GET" queryParameter="query">
<parameters>
<parameter name="output" value="json"/>
</parameters>
</endpointType>
</endpointTypes>
<datasources>
<codelist xml:id="languages" endpointType="virtuoso">
<uri>http://inspire-registry.jrc.ec.europa.eu/registers/Languages/items</uri>
<url>http://sparql/sparql.get-it.it/sparql</url>
</codelist>
<sparql xml:id="keywordsold" endpointType="virtuoso">
<query><![CDATA[
                
                        PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
                        SELECT ?c ?l ?a
                        FROM <http://ritmare.it/rdfdata/parameters>
                        WHERE { 
                          ?c rdf:type skos:Concept.
                          OPTIONAL {
                            ?c skos:prefLabel ?l.
                            FILTER( LANG(?l) = "en")
                          }
                          OPTIONAL {
                            ?c skos:prefLabel ?a.
                            FILTER( LANG(?a) = "it")
                          }
                          FILTER( REGEX( STR(?l), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                        }
                        ORDER BY ASC(?l) ASC(?a) 
                        
            ]]></query>
</sparql>
<singleton xml:id="keywordsSold" endpointType="virtuoso" triggerItem="output_param_1_uri">
<query><![CDATA[
                
                        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                        SELECT ?c ?l ?a
                        FROM <http://ritmare.it/rdfdata/parameters>
                        WHERE {
                          ?c rdf:type skos:Concept.
                          OPTIONAL {
                            ?c skos:prefLabel ?l.
                            FILTER( LANG(?l) = "en")
                          }
                          OPTIONAL {
                            ?c skos:prefLabel ?a.
                            FILTER( LANG(?a) = "it")
                          }
                          FILTER( REGEX( STR(?c), "$search_param", "i") || REGEX( STR(?a), "$search_param", "i") )
                        }
                        ORDER BY ASC(?l) ASC(?a)
                        
            ]]></query>
</singleton>
<sparql xml:id="keywords" endpointType="sparqlTemaTres">
<query><![CDATA[
                
                        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                         SELECT ?c ?l ?a
                         WHERE {
                            ?c rdf:type skos:Concept.
                            ?c skos:inScheme <http://openskos.lifewatchitaly.eu/PhytoTraits/>.
                            ?c skos:prefLabel ?l.
                            #<http://openskos.lifewatchitaly.eu/PhytoTraits/?tema=130> skos:narrower ?c.
                            OPTIONAL {
                                ?c skos:prefLabel ?a.
                                FILTER( LANG(?a) = "it")
                              }
                            FILTER REGEX( STR(?l), "$search_param", "i")
                        }
                        ORDER BY ASC(?l)
                        
            ]]></query>
<url>http://openskos.lifewatchitaly.eu/PhytoTraits/sparql.php</url>
</sparql>
<singleton xml:id="keywordsS" endpointType="sparqlTemaTres" triggerItem="output_param_1_uri">
<query><![CDATA[
                
                        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
                         SELECT ?c ?l ?a
                         WHERE {
                            ?c rdf:type skos:Concept.
                            ?c skos:inScheme <http://openskos.lifewatchitaly.eu/PhytoTraits/>.
                            ?c skos:prefLabel ?l.
                            #<http://openskos.lifewatchitaly.eu/PhytoTraits/?tema=130> skos:narrower ?c.
                            OPTIONAL {
                                ?c skos:prefLabel ?a.
                                FILTER( LANG(?a) = "it")
                              }
                            FILTER REGEX( STR(?l), "$search_param", "i")
                        }
                        ORDER BY ASC(?l)
                        
            ]]></query>
</singleton>
<singleton xml:id="manufacturers" endpointType="virtuoso">
<query><![CDATA[
                
                        PREFIX ns: <http://www.w3.org/2006/vcard/ns#>                        
                        SELECT ?c ?l 
                        FROM <http://ritmare.it/rdfdata/manufacturers>
                        WHERE { 
                          ?c rdf:type foaf:Organization.
                          ?c foaf:name ?l.
                          FILTER( REGEX( STR(?l), "$search_param", "i") )
                        }
                        ORDER BY ASC(?l)                        
                        
            ]]></query>
</singleton>
<singleton xml:id="info_manufacturers" endpointType="virtuoso" triggerItem="manuf_name_3_uri">
<query><![CDATA[
                
                        PREFIX addr: <http://wymiwyg.org/ontologies/foaf/postaddress#>
                        PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
                        SELECT ?phone fn:concat(?l1, ', ', ?l2) AS ?addr ?town ?region ?postcode ?country ?email ?homepage
                        FROM <http://ritmare.it/rdfdata/manufacturers>
                        WHERE { 
                          OPTIONAL {
                            <$search_param> foaf:phone ?phone .
                          }
                          OPTIONAL {
                            <$search_param> vcard:email ?email.
                          }
                          OPTIONAL {
                            <$search_param> foaf:homepage ?homepage.
                          }
                          OPTIONAL {
                            <$search_param> addr:address ?b1.
                          }
                          OPTIONAL {
                            ?b1 addr:deliveryPoint ?b2.
                          }
                          OPTIONAL {
                            ?b2 addr:location ?b3.
                          }
                          OPTIONAL {
                            ?b3 addr:thoroughfareName ?l1.
                          }
                          OPTIONAL {
                            ?b3 addr:streetNr ?l2.
                          }
                          OPTIONAL {
                            ?b3 addr:town ?town.
                          }
